/*
 * Copyright 2010-2026 Branimir Karadzic. All rights reserved.
 * License: https://github.com/bkaradzic/bnet/blob/master/LICENSE
 */

#ifndef BNET_CONFIG_H_HEADER_GUARD
#define BNET_CONFIG_H_HEADER_GUARD

#include <bx/bx.h>

#ifndef BNET_CONFIG_DEBUG
#	define BNET_CONFIG_DEBUG 0
#endif // BNET_CONFIG_DEBUG

#ifndef BNET_CONFIG_MBEDTLS
#	define BNET_CONFIG_MBEDTLS (!BX_PLATFORM_WINDOWS)
#endif // BNET_CONFIG_MBEDTLS

#ifndef BNET_CONFIG_WINSCHANNEL
#	define BNET_CONFIG_WINSCHANNEL (BX_PLATFORM_WINDOWS && !BNET_CONFIG_MBEDTLS)
#endif // BNET_CONFIG_WINSCHANNEL

#ifndef BNET_CONFIG_TLS
#	define BNET_CONFIG_TLS (0  \
	|| BNET_CONFIG_WINSCHANNEL \
	|| BNET_CONFIG_MBEDTLS     \
	)
#endif // BNET_CONFIG_TLS

#ifndef BNET_CONFIG_CONNECT_TIMEOUT_SECONDS
#	define BNET_CONFIG_CONNECT_TIMEOUT_SECONDS 5
#endif // BNET_CONFIG_CONNECT_TIMEOUT_SECONDS

#ifndef BNET_CONFIG_MAX_INCOMING_BUFFER_SIZE
#	define BNET_CONFIG_MAX_INCOMING_BUFFER_SIZE (64<<10)
#endif // BNET_CONFIG_MAX_INCOMING_BUFFER_SIZE

#endif // BNET_CONFIG_H_HEADER_GUARD
